bindings:
    # Example sequence bindings (acronyms).
    "asap;": "as soon as possible"
    # Example sequence bindings (german umlauts).
    "ae;": "ä"
    "Ae;": "Ä"
    "oe;": "ö"
    "Oe;": "Ö"
    "ue;": "ü"
    "Ue;": "Ü"
    "ss;": "ß"
    "Ss;": "ẞ"
